server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: ${spring.application.name}
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: user
          uri: lb://user-service
          predicates: [ Path=/users/** ]
        - id: product
          uri: lb://product-service
          predicates: [ Path=/products/**, /categories/** ]
        - id: order
          uri: lb://order-service
          predicates: [ Path=/orders/**, /cart/**, /stats/** ]
        - id: leader
          uri: lb://leader-service
          predicates: [ Path=/leaders/**, /communities/** ]
        - id: supplier
          uri: lb://supplier-service
          predicates: [ Path=/suppliers/**, /shipping/** ]
        - id: admin
          uri: lb://admin-service
          predicates: [ Path=/admin/** ]
